---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-example-deployment
  labels:
    app: ceph-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-example
  template:
    metadata:
      labels:
        app: ceph-example
    spec:
      containers:
      - name: ceph-example
        image: ubuntu
        command: ["sleep"]
        args: ["3600"]
        volumeMounts:
        - name: image-store
          mountPath: /mnt
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: example-pvc
          readOnly: false
